### ISSUE TITLE
quotes makes thing confusing

### ISSUE THREAD

**Issue by DreadKnight** [alexanderadam/rocksmith-2014-wine-docker#1]
> did not get it working. I'm running Rocksmith 2014 within a "real" Windows machine now (and it has bugs even there). I guess the repository could be finished but currently I'm not seeing what is missing.

Heya! Why do you put "real" in quotes? Virtualization or (dual) boot?

**Comment by alexanderadam** [comment]
I'm very sorry for the late response — I was eating.

> Heya! Why do you put "real" in quotes? Virtualization or (dual) boot?

I put the word `real` in quotes because I'm not using Wine, CrossOver or Proton.

**PS:** I'm impressed that someone found this repo :laughing:

**Comment by DreadKnight** [comment]
I struggled quite a bit to get the stuff running with Proton, but managed long time ago.

You sure eat a lot, lel xD
